apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
  labels:
    app: javaapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      nodeSelector:
        type: backend
      containers:
        - name: javaapp
          image: darshitsri/javaapp:latest
          ports:
            - containerPort: 8080
