apiVersion: apps/v1
kind: Deployment
metadata:
  name: java_app_deployment
  labels:
    app: java_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java_app
  template:
    metadata:
      labels:
        app: java_app
    spec:
      nodeSelector:
        type: backend
      containers:
        - name: java_app
          image: darshitsri/java_app:latest
          ports:
            - containerPort: 8080
