kind: Service
apiVersion: v1
metadata:
   name: java_appservice
   label:
      app: java_app
spec:
  selector:
     app: java_app
  type: NodePort
  ports:
  - Nodeport: 30036
    port: 80
    targetPort: 8080
