kind: Service
apiVersion: v1
metadata:
   name: demo_appservice
   label:
      app: demo_app
spec:
  selector:
     app: demo_app
  type: NodePort
  ports:
  - Nodeport: 30036
    port: 80
    targetPort: 8080
