replicaCount: 2

image:
  repository: darshitsri/java_app
  pullPolicy: IfNotPresent

service:
  type: NodePort
  #port: 8085
  port: 80
  targetport: 80
  #targetport: 8085
  name: springboot-app

container:
  name: my-springboot-app
