replicaCount: 2

image:
  repository: darshitsri/python-app
  pullPolicy: IfNotPresent

service:
  type: NodePort
  #port: 5000
  port: 80
  targetport: 80
  #targetport: 5000
  name: python-app

container:
  name: my-python-app
