name: Push Build to Artifactory
on: [push]
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
   # This action checks out the code from repository
   - name: Checkout Code
     uses: actions/checkout@v2
   - name: list directory
     run: pwd
#    - uses: jfrog/setup-jfrog-cli@v3
#      env:
#        JF_URL: ${{ secrets.JF_URL }}
#        JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

# #    # This action creates a new test file and uploads to Artifactory   
#    - name: Push Build to Artifactory
#      run: |
#        echo "JfrogRepoUrl " > JfrogRepoUrlJune.txt
#        export BUILD_NAME="my-build"
#        export BUILD_MODULE="my-module"
#        export BUILD_NUMBER="1"
#        export PATH_TO_DIRECTORY="test-exe-generic-local"
#        jf rt ping

#        jf rt u "JfrogRepoUrlJune.txt" $PATH_TO_DIRECTORY
