
on:
  push:
    branches: [ "java-application" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jfrog/setup-jfrog-cli@v3
      env:
    # JFrog platform url (for example: https://acme.jfrog.io) 
        JF_URL: ${{ secrets.JF_URL }}
    
    # Basic authentication credentials
        USER_JFROG: ${{ secrets.USER_JFROG }}
        PASS_JFROG: ${{ secrets.PASS_JFROG }}
    - run: |
       jf rt ping
       jf rt u test.txt test-exe-generic-local/
