
on:
  push:
    branches: [ "java-application" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: jfrog/setup-jfrog-cli@v3
      env:
    # JFrog platform url (for example: https://acme.jfrog.io) 
      JF_URL: https://jfrogtestlti.jfrog.io/
    
    # Basic authentication credentials
      USER_JFROG: ${{ secrets.JF_USER }}
      PASS_JFROG: ${{ secrets.JF_PASSWORD }}
    - run: |
       jf rt ping
