name: Java CI with Maven

on:
  push:
    branches: [ "java-application" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List the current directory
      run: ls -lrths
      
    - name: Switching to target
      run: |
        cd target
        ls -lrths
    - name: Sonar analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=darshitsri_project1  
    - name: docker images push
      run: |
       docker build -t darshitsri/java-githubaction_image:latest .
       echo "${{ secrets.DOCKER_PASS }}" | docker login -u "darshitsri" --password-stdin
       docker push darshitsri/java-githubaction_image:latest
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: /home/runner/work/project1/project1/target/springbootApp.jar
